Fix py-line-profiler incompatible decorators
Because `@run_after` and `@when` are incompatible (issue #12736), we got
the following error when installing py-line-profiler with Python 2.
```
/opt/spack/lib/spack/spack/package.py:1718, in build_process:
       1715                    echo = logger.echo
       1716                    self.log()
       1717
  >>   1718                # Run post install hooks before build stage is removed.
       1719                spack.hooks.post_install(self.spec)
       1720
       1721            # Stop timer.
NoSuchMethodError: Package PyLineProfiler does not support fix_cython called with py-line-profiler@2.1.2 [...] ^python@2.7.16 [...]
```

Change-Id: I2239ea86315aed7c65f750d0cfb369bb75a7b036