Only build library part of nghttp2
nghttp2 currently fails to build as it attempts to build its python bindings:

Making install in python
make[1]: Entering directory '/tmp/.../spack-stage/spack-stage-iatULv/nghttp2-1.26.0/python'
/usr/bin/python setup.py build
running build
running build_ext
make[2]: Entering directory '/tmp/.../spack-stage/spack-stage-iatULv/nghttp2-1.26.0/python'
/usr/bin/python setup.py install --prefix=/.../spack/opt/spack/linux-debian8-x86_64/gcc-4.9.2/nghttp2-1.26.0-nq5rdxyecyo7e3o5o6xtz6xblmizc3kk
running install
Checking .pth file support in /.../spack/opt/spack/linux-debian8-x86_64/gcc-4.9.2/nghttp2-1.26.0-nq5rdxyecyo7e3o5o6xtz6xblmizc3kk/lib/python2.7/site-packages/
/usr/bin/python -E -c pass
TEST FAILED: /.../spack/opt/spack/linux-debian8-x86_64/gcc-4.9.2/nghttp2-1.26.0-nq5rdxyecyo7e3o5o6xtz6xblmizc3kk/lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /.../spack/opt/spack/linux-debian8-x86_64/gcc-4.9.2/nghttp2-1.26.0-nq5rdxyecyo7e3o5o6xtz6xblmizc3kk/lib/python2.7/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
variable.  (It must then also be on PYTHONPATH whenever you run
Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
using one of the approaches described here:

https://pythonhosted.org/setuptools/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.